name = input('Enter your Name : ')
age = input ('Pleae Enter your Age here : ')
course = input ('Please State your Course : ')
matric = input('Input ur Matric No. : ')
university = input('Name of Institution: ')
print ('\n --- Student Information---')
print("Name: ", name)
print("Age: ", age)
print("Course: ", course)
print("Matric No: ", matric)
print("University: ", university )